// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnBUMrkvIGfN0Z_xCQNJQmLhSk8VtJ95c',
    appId: '1:597941196067:web:f6a18b674ba1c42176e896',
    messagingSenderId: '597941196067',
    projectId: 'lost-found-app-9430f',
    authDomain: 'lost-found-app-9430f.firebaseapp.com',
    storageBucket: 'lost-found-app-9430f.firebasestorage.app',
    measurementId: 'G-9XWLPE9W63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzbUzswQCpqxPXYKSltJAO9pfEJj3Svnk',
    appId: '1:597941196067:android:54c6997da535cc6976e896',
    messagingSenderId: '597941196067',
    projectId: 'lost-found-app-9430f',
    storageBucket: 'lost-found-app-9430f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLYAlRdhKHi7-DRo95i6WpEuXJ9O4qZU4',
    appId: '1:597941196067:ios:59f0ebc4a709e91a76e896',
    messagingSenderId: '597941196067',
    projectId: 'lost-found-app-9430f',
    storageBucket: 'lost-found-app-9430f.firebasestorage.app',
    iosBundleId: 'com.example.mapTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLYAlRdhKHi7-DRo95i6WpEuXJ9O4qZU4',
    appId: '1:597941196067:ios:59f0ebc4a709e91a76e896',
    messagingSenderId: '597941196067',
    projectId: 'lost-found-app-9430f',
    storageBucket: 'lost-found-app-9430f.firebasestorage.app',
    iosBundleId: 'com.example.mapTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnBUMrkvIGfN0Z_xCQNJQmLhSk8VtJ95c',
    appId: '1:597941196067:web:f862dcbc4aab419f76e896',
    messagingSenderId: '597941196067',
    projectId: 'lost-found-app-9430f',
    authDomain: 'lost-found-app-9430f.firebaseapp.com',
    storageBucket: 'lost-found-app-9430f.firebasestorage.app',
    measurementId: 'G-94X1BKGVZL',
  );
}
